# .prettierrc or .prettierrc.yaml
trailingComma: 'es5'
tabWidth: 2
semi: false
singleQuote: true
plugins:
  - '@trivago/prettier-plugin-sort-imports'
importOrder:
  - '^solid-js$'
  - '^@tanstack/solid-query$'
  - '^@tauri-apps/(.*)$'
  - '^@shared/(.*)$'
  - '^@/(.*)$'
  - '^[./]'
importOrderSeparation: true
importOrderSortSpecifiers: true
