[[language]]
name = "toml"
scope = "source.toml"
injection-regex = "toml"
file-types = ["toml"]
roots = []
language-servers = ["taplo"]
auto-format = true

[language-server.unocss]
command = "unocss-language-server"
args = ["--stdio"]
roots = ["unocss.config.ts"]

[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "typescript|ts"
file-types = ["ts"]
roots = ["package.json", "tsconfig.json"]
language-servers = ["typescript-language-server"]
auto-format = true

[[language]]
name = "tsx"
scope = "source.tsx"
injection-regex = "tsx"
file-types = ["tsx"]
roots = ["package.json", "tsconfig.json"]
language-servers = ["typescript-language-server", "unocss-language-server"]
auto-format = true

[[language]]
name = "javascript"
scope = "source.js"
injection-regex = "javascript|js"
file-types = ["js"]
roots = ["package.json"]
language-servers = ["typescript-language-server"]
auto-format = true

[[language]]
name = "jsx"
scope = "source.jsx"
injection-regex = "jsx"
file-types = ["jsx"]
roots = ["package.json"]
language-servers = ["typescript-language-server", "unocss-language-server"]
auto-format = true

[[language]]
name = "css"
scope = "source.css"
injection-regex = "css"
file-types = ["css"]
roots = ["package.json"]
language-servers = ["vscode-css-language-server", "unocss-language-server"]
auto-format = true

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
language-servers = ["rust-analyzer"]
auto-format = true

[[language]]
name = "yaml"
scope = "source.yaml"
injection-regex = "yaml"
file-types = ["yaml", "yml"]
roots = []
language-servers = ["yaml-language-server"]
auto-format = true
