// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceItemType } from "./workspace-item.type";

export type WorkspaceItemContext = { itemType: WorkspaceItemType, itemId: string, context: string | null, };
