// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceConfig } from "./workspace-config.type";

export type WorkspaceSelectConfig = { jsonConfig: WorkspaceConfig | null, };
