// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderAuthType } from "./provider-auth-type.type";
import type { ProviderModelsSyncStrategy } from "./provider-models-sync-strategy.type";

export type Provider = { id: string, marketplace_id: string | null, name: string, base_url: string, auth_type: ProviderAuthType, api_key_id: string | null, json_keys: string | null, json_variables: string | null, json_auth_config: string | null, models_sync_strategy: ProviderModelsSyncStrategy, updated_at: string, };
