// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NodeMessage = { id: string, content: string, versionNumber: bigint, status: string, nodeId: string, modelId: string | null, tokenCount: bigint | null, cost: number | null, jsonApiMetadata: string | null, jsonExtensions: string | null, updatedAt: string, };
