// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents extracted usage information from a stream.
 */
export type UsageInfo = { prompt_tokens: number | null, completion_tokens: number | null, total_tokens: number | null, };
